# Site settings
title: Data Science for Social Good 2015
email:
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uwescience.github.io/DSSG2015" # the base hostname & protocol for your site
twitter_username: uwescience
github_username:  uwescience

# Build settings
markdown: kramdown
