# Site settings
title: Data Science for Social Good 2015
email: arokem@gmail.com
description: "Data Science for Social Good"
baseurl: "" 
url: "http://uwescience.github.io/DSSG2015" 
twitter_username: uwescience
github_username:  uwescience

# Build settings
markdown: kramdown
