# Site settings
title: King County Metro Paratransit
email: kgarofali@gmail.com
description: "#DSSG2015 @uwescience"
baseurl: "http://uwescience.github.io/DSSG2015" 
url: "http://uwescience.github.io/DSSG-paratransit" 
twitter_username: uwescience
github_username:  uwescience

# Build settings
markdown: kramdown
